### ISSUE TITLE
Additional primer info

### ISSUE THREAD

**Issue by pommevilla** [pommevilla/ispcr#19]
# Primer set features

Expected output:

```
forward_primer:
    gc_content:
    melting_temperature:  

reverse_primer:
    gc_content:
    melting_temperature
```
